#!bin/zsh

. $HOME/.Xresources.d/color/ex_colors

# Fonts
FONT1="-gohu-gohufont-medium-r-normal--11-80-100-100-c-60-iso8859-1"
FONT2="-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1"
FONT3="siji"
FONT4="-benis-lemon-medium-r-normal--10-110-75-75-m-50-iso8859-1"
FONT5="boxxy"
FONT6="-kakwa-kakwafont-medium-r-normal--12-120-72-72-c-60-iso8859-1"


# Panel 
PW=300
PH=48
PX=533
PY=372

echo "%{c}%{F$BLUE}%{F} %{F$FG}%{A:p:}Shutdown%{A}  %{A:r:}Reboot%{A}  %{A:s:}Suspend%{A}  %{A:b:}Exit%{A}%{F}  " | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT3" -f "$FONT5" -B "$BG" -F "$FG" -dp | \
    while :; do
        read line
        case $line in 
            'b')
                p=$(pgrep -n lemonbar)
                kill $p 
                exit 
                ;;
            's')
                /usr/sbin/pm-suspend &
                p=$(pgrep -n lemonbar)
                kill $p 
                exit                
                ;;
            'p')
                poweroff
                exit
                ;;
            'r')
                /sbin/shutdown -r now
                exit
                ;;
        esac
    done

